version: '2'
services: 
    web:
        image: nginx:1.17
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./todos/static:/usr/share/nginx/html/static
        ports:
            - 8080:80
    app:
        build: todos