# Generated by Django 3.0.4 on 2020-03-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('notes', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
