# Generated by Django 3.0.4 on 2020-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due',
            field=models.DateField(null=True),
        ),
    ]
